package vista;

import java.awt.Dimension;
import controlador.Ctrl_Producto;
import controlador.Ctrl_Categoria;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Producto;
import modelo.Categoria;

import javax.swing.JInternalFrame;

public class InterProducto extends javax.swing.JInternalFrame {

    int obtenerIdCategoriaCombo = 0;
    private Ctrl_Producto controlProducto;
    private Ctrl_Categoria controlCategoria;

    public InterProducto() {
        initComponents();
        controlProducto = new Ctrl_Producto();
        controlCategoria = new Ctrl_Categoria();
        this.setSize(new Dimension(400, 330));
        this.setTitle("Nuevo Producto");
        cargarCategorias();
        limpiarCampos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // ============================================================
    // ✅ MÉTODO 1: CARGAR CATEGORÍAS EN EL COMBOBOX
    // ============================================================
    private void cargarCategorias() {
        jComboBox_categoria.removeAllItems();
        jComboBox_categoria.addItem("Seleccione categoría...");

        List<Categoria> lista = controlCategoria.listarCategorias();
        if (lista != null) {
            for (Categoria cat : lista) {
                jComboBox_categoria.addItem(cat.getDescripcion());
            }
        }
    }

    // ============================================================
    // ✅ MÉTODO 2: OBTENER ID DE CATEGORÍA SELECCIONADA
    // ============================================================
    private int obtenerIdCategoria(String nombreCategoria) {
        List<Categoria> lista = controlCategoria.listarCategorias();
        if (lista != null) {
            for (Categoria cat : lista) {
                if (cat.getDescripcion().equals(nombreCategoria)) {
                    return cat.getIdCategoria();  // ✅ CORRECTO
                }
            }
        }
        return 0;
    }

    // ============================================================
    // ✅ MÉTODO 3: OBTENER PORCENTAJE DE IVA
    // ============================================================
    private int obtenerPorcentajeIVA(String ivaSeleccionado) {
        if (ivaSeleccionado.equals("12%")) {
            return 12;
        }
        if (ivaSeleccionado.equals("14%")) {
            return 14;
        }
        if (ivaSeleccionado.equals("No grava iva:")) {
            return 0;
        }
        return 0;
    }

    // ============================================================
    // ✅ MÉTODO 4: LIMPIAR CAMPOS
    // ============================================================
    private void limpiarCampos() {
        txt_nombre.setText("");
        txt_cantidad.setText("");
        txt_precio.setText("");
        txt_descripcion.setText("");
        jComboBox_iva.setSelectedIndex(0);
        jComboBox_categoria.setSelectedIndex(0);
        txt_nombre.requestFocus();
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_cantidad = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        txt_descripcion = new javax.swing.JTextField();
        jComboBox_iva = new javax.swing.JComboBox<>();
        jComboBox_categoria = new javax.swing.JComboBox<>();
        jButton_Guardar = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setForeground(java.awt.Color.white);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nuevo Producto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 90, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Cantidad");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 90, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Precio:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 90, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Descripcion:");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 90, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("IVA:");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 90, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Categorias:");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 90, -1));

        txt_nombre.addActionListener(this::txt_nombreActionPerformed);
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 170, -1));

        txt_cantidad.addActionListener(this::txt_cantidadActionPerformed);
        getContentPane().add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 170, -1));

        txt_precio.addActionListener(this::txt_precioActionPerformed);
        getContentPane().add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 170, -1));

        txt_descripcion.addActionListener(this::txt_descripcionActionPerformed);
        getContentPane().add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 170, -1));

        jComboBox_iva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione iva:", "No grava iva:", "12%", "14%" }));
        getContentPane().add(jComboBox_iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 170, 30));

        jComboBox_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione categoria:", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 170, -1));

        jButton_Guardar.setBackground(new java.awt.Color(0, 204, 204));
        jButton_Guardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Guardar.setText("Guardar");
        jButton_Guardar.addActionListener(this::jButton_GuardarActionPerformed);
        getContentPane().add(jButton_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 243, 90, 30));

        jLabel_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidadActionPerformed

    private void txt_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_precioActionPerformed

    private void txt_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descripcionActionPerformed

    private void jButton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarActionPerformed
        // Validar campos vacíos
        if (txt_nombre.getText().isEmpty() || txt_cantidad.getText().isEmpty()
                || txt_precio.getText().isEmpty() || txt_descripcion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "COMPLETE TODOS LOS CAMPOS");
            return;
        }

        // Validar que cantidad y precio sean números
        try {
            Integer.parseInt(txt_cantidad.getText().trim());
            Double.parseDouble(txt_precio.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Cantidad y Precio deben ser números válidos");
            return;
        }

        // Validar categoría seleccionada
        String categoriaSeleccionada = (String) jComboBox_categoria.getSelectedItem();
        if (categoriaSeleccionada == null || categoriaSeleccionada.equals("Seleccione categoría...")) {
            JOptionPane.showMessageDialog(this, "SELECCIONE UNA CATEGORÍA");
            return;
        }

        // Validar IVA seleccionado
        String ivaSeleccionado = (String) jComboBox_iva.getSelectedItem();
        if (ivaSeleccionado == null || ivaSeleccionado.equals("Seleccione iva:")) {
            JOptionPane.showMessageDialog(this, "SELECCIONE UN IVA");
            return;
        }

        // Crear objeto Producto
        Producto producto = new Producto();
        producto.setNombre(txt_nombre.getText().trim());
        producto.setCantidad(Integer.parseInt(txt_cantidad.getText().trim()));
        producto.setPrecio(Double.parseDouble(txt_precio.getText().trim()));
        producto.setDescripcion(txt_descripcion.getText().trim());
        producto.setPorcentajeIVA(obtenerPorcentajeIVA(ivaSeleccionado));
        producto.setIdCategoria(obtenerIdCategoria(categoriaSeleccionada));
        producto.setEstado(1);

        // Verificar si el producto ya existe
        if (controlProducto.existeProducto(producto.getNombre())) {
            JOptionPane.showMessageDialog(this, "El producto '" + producto.getNombre() + "' ya existe");
            return;
        }

        // Guardar producto
        if (controlProducto.guardar(producto)) {
            JOptionPane.showMessageDialog(this, "¡PRODUCTO REGISTRADO!");
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "¡ERROR AL REGISTRAR EL PRODUCTO!");
        }
    }//GEN-LAST:event_jButton_GuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Guardar;
    private javax.swing.JComboBox<String> jComboBox_categoria;
    private javax.swing.JComboBox<String> jComboBox_iva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables
}
